/// <reference path="android-declarations.d.ts"/>

declare module com {
	export module example {
		export module tscdll {
			export class TSCActivity {
				public static class: java.lang.Class<com.example.tscdll.TSCActivity>;
				public IsConnected: boolean;
				public printername(param0: number): string;
				public printlabel(param0: number, param1: number): string;
				public sendpicture_resize(param0: number, param1: number, param2: string, param3: number, param4: number): void;
				public status(param0: number): string;
				public closeport(param0: number): string;
				public downloadttf(param0: string): string;
				public downloadfile_absolutePath(param0: string, param1: string): string;
				public downloadfile(param0: java.io.File, param1: string): string;
				public printermileage(): string;
				public lineGrey(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public printercodepage(param0: number): string;
				public gray2Binary(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public pdf_gray_save(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public sendcommandGB2312(param0: string, param1: number): string;
				public onStart(): void;
				public openport(param0: string, param1: number): string;
				public formfeed(): string;
				public sendbitmap(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap): void;
				public setup(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number): string;
				public static getHexString(param0: native.Array<number>): string;
				public WiFi_SSID(param0: string): string;
				public pdf_color_resize(param0: number, param1: number, param2: java.io.File, param3: number, param4: number): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public openport_with_pair(param0: number): string;
				public sendcommand_getstring(param0: string): string;
				public printerstatus_byte(param0: number): number;
				public downloadpcx(param0: string): string;
				public status(): string;
				public bitmap2Gray(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public printerstatus(param0: number): string;
				public barcode(param0: number, param1: number, param2: string, param3: number, param4: number, param5: number, param6: number, param7: number, param8: string): string;
				public pdf_gray_resize(param0: number, param1: number, param2: java.io.File, param3: number, param4: number): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public openport_without_security(param0: string, param1: number): string;
				public status(param0: number, param1: number): string;
				public sendpicture_resize_halftone(param0: number, param1: number, param2: string, param3: number, param4: number): void;
				public openport_without_security(param0: string): string;
				public windowsfont(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap): string;
				public static byteArrayToHex(param0: native.Array<number>): string;
				public WiFi_Default(): string;
				public pdf_color(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public pdf_gray(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public printermemory(param0: number): string;
				public qrcode(param0: number, param1: number, param2: string, param3: string, param4: string, param5: string, param6: string, param7: string, param8: string): string;
				public downloadfile_absolutePath(param0: java.io.File, param1: string): string;
				public printerfont(param0: number, param1: number, param2: string, param3: number, param4: number, param5: number, param6: string): string;
				public sendfile(param0: string, param1: string): string;
				public windowsfont(param0: number, param1: number, param2: number, param3: string, param4: string): string;
				public WiFi_WEP(param0: number, param1: string): string;
				public sendcommandUTF8(param0: string): string;
				public return_file_byte(param0: string, param1: string): native.Array<number>;
				public sendpicture_CPCL(param0: number, param1: number, param2: string): void;
				public NFC_Timeout(param0: number): number;
				public printerfile(param0: number): string;
				public NFC_Write_data(param0: string): number;
				public sendcommand(param0: native.Array<number>): string;
				public sendbitmap_resize(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap, param3: number, param4: number): void;
				public printerstatus(): string;
				public sendcommand(param0: string): string;
				public constructor();
				public sendcommand(param0: string, param1: number): string;
				public WiFi_DHCP(): string;
				public WiFi_WPA(param0: string): string;
				public closeport(): string;
				public send_file_data(param0: string, param1: native.Array<number>): string;
				public queryprinter(param0: number): string;
				public onResume(): void;
				public restart(): string;
				public printer_completestatus(param0: number): string;
				public openport_onpair_btname(param0: string): string;
				public sendcommandGB2312(param0: string): string;
				public sendbitmap_gray_resize(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap, param3: number, param4: number): void;
				public downloadfile(param0: string, param1: string, param2: string): string;
				public nobackfeed(): string;
				public sendpicture_halftone(param0: number, param1: number, param2: string): void;
				public sendcommandBig5(param0: string): string;
				public downloadbmp(param0: string): string;
				public openport_with_pair(): string;
				public pdf_color_save(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public bar(param0: string, param1: string, param2: string, param3: string): string;
				public sendcommand_getstring(param0: string, param1: number): string;
				public printername(): string;
				public onPause(): void;
				public clearbuffer(): string;
				public sendcommand(param0: native.Array<number>, param1: number): string;
				public WiFi_StaticIP(param0: string, param1: string, param2: string): string;
				public smartbattery_status(param0: number): string;
				public openport(param0: string): string;
				public queryprinter(): string;
				public onStop(): void;
				public printer_completestatus(): string;
				public printermemory(): string;
				public gray2halftone(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public printermileage(param0: number): string;
				public printerfile(): string;
				public onCreateOptionsMenu(param0: globalAndroid.view.Menu): boolean;
				public sendfile(param0: string): string;
				public WiFi_Port(param0: number): string;
				public printercodepage(): string;
				public openport_onpair_btname(param0: string, param1: number): string;
				public downloadfile(param0: string, param1: string): string;
				public onCreate(param0: globalAndroid.os.Bundle): void;
				public NFC_Read_data(param0: number): string;
				public onDestroy(): void;
				public sendpicture(param0: number, param1: number, param2: string): void;
				public printerstatus_byte(): number;
			}
		}
	}
}

declare module com {
	export module example {
		export module tscdll {
			export class TSCUSBActivity {
				public static class: java.lang.Class<com.example.tscdll.TSCUSBActivity>;
				public mUsbManager: globalAndroid.hardware.usb.UsbManager;
				public mUsbDevice: globalAndroid.hardware.usb.UsbDevice;
				public static LED_SERVO_COMMAND: number;
				public static RELAY_COMMAND: number;
				public sendcommand(param0: string): string;
				public sendcommand_largebyte(param0: native.Array<number>): string;
				public printlabel(param0: number, param1: number): string;
				public printername(param0: number): string;
				public checkInfo(): void;
				public constructor();
				public WiFi_DHCP(): string;
				public status(param0: number): string;
				public closeport(param0: number): string;
				public WiFi_WPA(param0: string): string;
				public closeport(): string;
				public downloadttf(param0: string): string;
				public downloadfile_absolutePath(param0: string, param1: string): string;
				public send_file_data(param0: string, param1: native.Array<number>): string;
				public threadopen(): void;
				public queryprinter(param0: number): string;
				public downloadfile(param0: java.io.File, param1: string): string;
				public restart(): string;
				public printermileage(): string;
				public lineGrey(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public printercodepage(param0: number): string;
				public openport(param0: globalAndroid.hardware.usb.UsbManager, param1: globalAndroid.hardware.usb.UsbDevice): string;
				public sendcommandGB2312(param0: string): string;
				public msendbythread(): void;
				public sendcommand_without_delay(param0: native.Array<number>): string;
				public downloadfile(param0: string, param1: string, param2: string): string;
				public nobackfeed(): string;
				public sendpicture_halftone(param0: number, param1: number, param2: string): void;
				public gray2Binary(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public pdf_gray_save(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public sendpicture(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap): void;
				public sendcommandBig5(param0: string): string;
				public formfeed(): string;
				public downloadbmp(param0: string): string;
				public setup(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number): string;
				public printer_completestatus(param0: number, param1: number): string;
				public pdf_color_save(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public WiFi_SSID(param0: string): string;
				public bar(param0: string, param1: string, param2: string, param3: string): string;
				public openport(param0: globalAndroid.hardware.usb.UsbManager, param1: globalAndroid.hardware.usb.UsbDevice, param2: number): string;
				public pdf_color_resize(param0: number, param1: number, param2: java.io.File, param3: number, param4: number): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public sendcommand_getstring(param0: string): string;
				public printername(): string;
				public downloadpcx(param0: string): string;
				public printerstatus_byte(param0: number): number;
				public status(): string;
				public bitmap2Gray(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public barcode(param0: number, param1: number, param2: string, param3: number, param4: number, param5: number, param6: number, param7: number, param8: string): string;
				public printerstatus(param0: number): string;
				public pdf_gray_resize(param0: number, param1: number, param2: java.io.File, param3: number, param4: number): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public status(param0: number, param1: number): string;
				public clearbuffer(): string;
				public windowsfont(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap): string;
				public static byteArrayToHex(param0: native.Array<number>): string;
				public WiFi_Default(): string;
				public WiFi_StaticIP(param0: string, param1: string, param2: string): string;
				public pdf_color(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public pdf_gray(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public run(): void;
				public printermemory(param0: number): string;
				public smartbattery_status(param0: number): string;
				public queryprinter(): string;
				public qrcode(param0: number, param1: number, param2: string, param3: string, param4: string, param5: string, param6: string, param7: string, param8: string): string;
				public printer_completestatus(): string;
				public open(): void;
				public printermemory(): string;
				public downloadfile_absolutePath(param0: java.io.File, param1: string): string;
				public printerfont(param0: number, param1: number, param2: string, param3: number, param4: number, param5: number, param6: string): string;
				public sendfile(param0: string, param1: string): string;
				public gray2halftone(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public windowsfont(param0: number, param1: number, param2: number, param3: string, param4: string): string;
				public printermileage(param0: number): string;
				public printerfile(): string;
				public onCreateOptionsMenu(param0: globalAndroid.view.Menu): boolean;
				public sendfile(param0: string): string;
				public WiFi_Port(param0: number): string;
				public WiFi_WEP(param0: number, param1: string): string;
				public sendcommandUTF8(param0: string): string;
				public return_file_byte(param0: string, param1: string): native.Array<number>;
				public send_file_data_without_delay(param0: string, param1: native.Array<number>): string;
				public printercodepage(): string;
				public sendpicture_CPCL(param0: number, param1: number, param2: string): void;
				public downloadfile(param0: string, param1: string): string;
				public NFC_Timeout(param0: number): number;
				public printerfile(param0: number): string;
				public onCreate(param0: globalAndroid.os.Bundle): void;
				public NFC_Write_data(param0: string): number;
				public mopen(): void;
				public NFC_Read_data(param0: number): string;
				public sendcommand(param0: native.Array<number>): string;
				public sendpicture(param0: number, param1: number, param2: string): void;
				public printerstatus_byte(): number;
				public printerstatus(): string;
			}
		}
	}
}

declare module com {
	export module example {
		export module tscdll {
			export class TscWifiActivity {
				public static class: java.lang.Class<com.example.tscdll.TscWifiActivity>;
				public UDP_NAME: native.Array<string>;
				public UDP_IP: native.Array<string>;
				public UDP_MAC: native.Array<string>;
				public UDP_status: native.Array<string>;
				public openport_time(param0: string, param1: number, param2: number): string;
				public printername(param0: number): string;
				public printlabel(param0: number, param1: number): string;
				public status(param0: number): string;
				public closeport(param0: number): string;
				public downloadttf(param0: string): string;
				public downloadfile_absolutePath(param0: string, param1: string): string;
				public sendcommand_thread(param0: string): string;
				public downloadfile(param0: java.io.File, param1: string): string;
				public printermileage(): string;
				public lineGrey(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public printercodepage(param0: number): string;
				public gray2Binary(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public pdf_gray_save(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public onStart(): void;
				public openport(param0: string, param1: number): string;
				public formfeed(): string;
				public sendbitmap(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap): void;
				public setup(param0: number, param1: number, param2: number, param3: number, param4: number, param5: number, param6: number): string;
				public WiFi_SSID(param0: string): string;
				public pdf_color_resize(param0: number, param1: number, param2: java.io.File, param3: number, param4: number): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public sendcommand_getstring(param0: string): string;
				public printerstatus_byte(param0: number): number;
				public downloadpcx(param0: string): string;
				public status(): string;
				public bitmap2Gray(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public printerstatus(param0: number): string;
				public barcode(param0: number, param1: number, param2: string, param3: number, param4: number, param5: number, param6: number, param7: number, param8: string): string;
				public pdf_gray_resize(param0: number, param1: number, param2: java.io.File, param3: number, param4: number): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public status(param0: number, param1: number): string;
				public windowsfont(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap): string;
				public static byteArrayToHex(param0: native.Array<number>): string;
				public pdf_color(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public pdf_gray(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public WiFi_Default(): string;
				public printermemory(param0: number): string;
				public qrcode(param0: number, param1: number, param2: string, param3: string, param4: string, param5: string, param6: string, param7: string, param8: string): string;
				public downloadfile_absolutePath(param0: java.io.File, param1: string): string;
				public printerfont(param0: number, param1: number, param2: string, param3: number, param4: number, param5: number, param6: string): string;
				public sendfile(param0: string, param1: string): string;
				public windowsfont(param0: number, param1: number, param2: number, param3: string, param4: string): string;
				public WiFi_WEP(param0: number, param1: string): string;
				public sendcommandUTF8(param0: string): string;
				public return_file_byte(param0: string, param1: string): native.Array<number>;
				public sendpicture_CPCL(param0: number, param1: number, param2: string): void;
				public NFC_Timeout(param0: number): number;
				public printerfile(param0: number): string;
				public NFC_Write_data(param0: string): number;
				public sendcommand(param0: native.Array<number>): string;
				public sendbitmap_resize(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap, param3: number, param4: number): void;
				public printerstatus(): string;
				public sendcommand(param0: string): string;
				public constructor();
				public restart(): void;
				public WiFi_DHCP(): string;
				public WiFi_WPA(param0: string): string;
				public closeport(): string;
				public send_file_data(param0: string, param1: native.Array<number>): string;
				public queryprinter(param0: number): string;
				public onResume(): void;
				public printer_completestatus(param0: number): string;
				public sendcommandGB2312(param0: string): string;
				public sendbitmap_gray_resize(param0: number, param1: number, param2: globalAndroid.graphics.Bitmap, param3: number, param4: number): void;
				public downloadfile(param0: string, param1: string, param2: string): string;
				public nobackfeed(): string;
				public sendpicture_halftone(param0: number, param1: number, param2: string): void;
				public sendcommandBig5(param0: string): string;
				public downloadbmp(param0: string): string;
				public pdf_color_save(param0: number, param1: number, param2: java.io.File): java.util.ArrayList<globalAndroid.graphics.Bitmap>;
				public bar(param0: string, param1: string, param2: string, param3: string): string;
				public printername(): string;
				public sendcommand_getstring(param0: string, param1: number): string;
				public onPause(): void;
				public clearbuffer(): string;
				public WiFi_StaticIP(param0: string, param1: string, param2: string): string;
				public smartbattery_status(param0: number): string;
				public queryprinter(): string;
				public onStop(): void;
				public printer_completestatus(): string;
				public Discovery_UDP(param0: number): void;
				public printermemory(): string;
				public openport_thread(param0: string, param1: number): string;
				public gray2halftone(param0: globalAndroid.graphics.Bitmap): globalAndroid.graphics.Bitmap;
				public printermileage(param0: number): string;
				public printerfile(): string;
				public onCreateOptionsMenu(param0: globalAndroid.view.Menu): boolean;
				public sendfile(param0: string): string;
				public WiFi_Port(param0: number): string;
				public openport(param0: string, param1: number, param2: number): string;
				public printercodepage(): string;
				public Discovery_UDP_Thread(): void;
				public downloadfile(param0: string, param1: string): string;
				public onCreate(param0: globalAndroid.os.Bundle): void;
				public openport_thread(param0: string, param1: number, param2: number): string;
				public NFC_Read_data(param0: number): string;
				public onDestroy(): void;
				public sendpicture(param0: number, param1: number, param2: string): void;
				public printerstatus_byte(): number;
			}
		}
	}
}

//Generics information:
